# Generated by Django 3.1.1 on 2020-09-11 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200911_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='eamil_verified',
            new_name='email_verified',
        ),
    ]
